WIFI_SSID = "YOUR_WIFI_NAME"
WIFI_PASS = "YOUR_WIFI_PASS"

CLIENT_ID = "YOUR_CLIENT_ID_HERE"
CLIENT_SECRET = "YOUR_CLIENT_SECRET_HERE"
REDIRECT_URI = "http://localhost:8888/callback"

DISPLAY_ROTATE = 0
DISPLAY_CONTRAST = 128
SPOTIFY_POLL_INTERVAL = 10
KEY0_PIN = 15
KEY1_PIN = 17
